
import __ASTRO_IMAGE_IMPORT_ZeG13f from "../../assets/blog/blog-1.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fblogs%2Fwebsites-that-convert.md";
import __ASTRO_IMAGE_IMPORT_Z1mdRpW from "../../assets/blog/blog-2.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fblogs%2Fsmarter-ai-workflows.md";
import __ASTRO_IMAGE_IMPORT_Z2glH2m from "../../assets/blog/blog-3.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fblogs%2Fstartup-automation-leverage.md";
import __ASTRO_IMAGE_IMPORT_2sz14o from "../../assets/works/banyan-studio/banyan-01.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Fbanyan-studio.mdx";
import __ASTRO_IMAGE_IMPORT_2cv7J from "../../assets/works/cipres-agency/cipres-agency-01.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Fcipres-agency.mdx";
import __ASTRO_IMAGE_IMPORT_1Fyh27 from "../../assets/works/cipres-energy/cipres-energy-01.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Fcipres-energy.mdx";
import __ASTRO_IMAGE_IMPORT_ZXxJXX from "../../assets/works/larch-agency/larch-01.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Flarch-agency.mdx";
import __ASTRO_IMAGE_IMPORT_1jkRbi from "../../assets/works/olmo-studio/olmo-01.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Folmo-studio.mdx";
export default new Map([["../../assets/blog/blog-1.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fblogs%2Fwebsites-that-convert.md", __ASTRO_IMAGE_IMPORT_ZeG13f], ["../../assets/blog/blog-2.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fblogs%2Fsmarter-ai-workflows.md", __ASTRO_IMAGE_IMPORT_Z1mdRpW], ["../../assets/blog/blog-3.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fblogs%2Fstartup-automation-leverage.md", __ASTRO_IMAGE_IMPORT_Z2glH2m], ["../../assets/works/banyan-studio/banyan-01.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Fbanyan-studio.mdx", __ASTRO_IMAGE_IMPORT_2sz14o], ["../../assets/works/cipres-agency/cipres-agency-01.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Fcipres-agency.mdx", __ASTRO_IMAGE_IMPORT_2cv7J], ["../../assets/works/cipres-energy/cipres-energy-01.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Fcipres-energy.mdx", __ASTRO_IMAGE_IMPORT_1Fyh27], ["../../assets/works/larch-agency/larch-01.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Flarch-agency.mdx", __ASTRO_IMAGE_IMPORT_ZXxJXX], ["../../assets/works/olmo-studio/olmo-01.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Folmo-studio.mdx", __ASTRO_IMAGE_IMPORT_1jkRbi]]);
		