// Automatically generated by astro-icon
// 2fdf5470d84d62e397955a7c4ea15d44c759d46edeece1c6fb6fc0d081adab17

declare module 'virtual:astro-icon' {
	export type Icon = 
		| "arrow"
		| "asterisk"
		| "chevron"
		| "globe"
		| "logo-brands/banyan-logo"
		| "logo-brands/cipres-agency-logo"
		| "logo-brands/cipres-energy-logo"
		| "logo-brands/larch-logo"
		| "logo-brands/logoipsum-1"
		| "logo-brands/logoipsum-2"
		| "logo-brands/logoipsum-3"
		| "logo-brands/logoipsum-4"
		| "logo-brands/logoipsum-5"
		| "logo-brands/logoipsum-6"
		| "logo-brands/olmo-logo"
		| "menu"
		| "plus"
		| "socials/facebook"
		| "socials/instagram"
		| "socials/linkedin"
		| "socials/x"
		| "spin"
		| "world";
}