import { type RouteConfig, index, route } from "@react-router/dev/routes";

export default [
  index("routes/_index.tsx"),
  route("articles", "routes/articles._index.tsx"),
  route("articles/:slug", "routes/articles.$slug.tsx"),
  route("articles/:slug/p/:page", "routes/articles.$slug.p$page.tsx"),
  route("about", "routes/about.tsx"),
  route("representative", "routes/representative.tsx"),
  route("knowledge", "routes/knowledge._index.tsx"),
  route("knowledge/:slug", "routes/knowledge.$slug.tsx"),
  route("glossary", "routes/glossary.tsx"),
  route("media/*", "routes/media.$.ts"),
  route("api/sync/media", "routes/api.sync.media.ts"),
  route("api/sync/content", "routes/api.sync.content.ts"),
  route("api/sync/faqs", "routes/api.sync.faqs.ts"),
  route("api/crawler-stats", "routes/api.crawler-stats.ts"),
  route("api/chat", "routes/api.chat.ts"),
  route("api/patrol-results", "routes/api.patrol-results.ts"),
  route("api/analytics", "routes/api.analytics.ts"),
  route("api/index-articles", "routes/api.index-articles.ts"),
  route("api/ingest-external", "routes/api.ingest-external.ts"),
  route("api/generate-panel-faqs", "routes/api.generate-panel-faqs.ts"),
  route("api/generate-panel-glossary", "routes/api.generate-panel-glossary.ts"),
  route("api/structured-data", "routes/api.structured-data.ts"),
  route("llms.txt", "routes/llms[.]txt.ts"),
  route("llms-full.txt", "routes/llms-full[.]txt.ts"),
  route("robots.txt", "routes/robots[.]txt.ts"),
  route("sitemap.xml", "routes/sitemap[.]xml.ts"),
  route(".well-known/ai-plugin.json", "routes/$.well-known.ai-plugin[.]json.ts"),
  route(".well-known/openapi.json", "routes/$.well-known.openapi[.]json.ts"),
] satisfies RouteConfig;
